address = "ADDRESS"; age = "AGE"
aws_access = "AWS_ACCESS_KEY"; aws_secret = "AWS_SECRET_KEY"
bank_acc = "BANK_ACCOUNT_NUMBER"; bank_route = "BANK_ROUTING"
credit_cvv = "CREDIT_DEBIT_CVV"; credit_expiry = "CREDIT_DEBIT_EXPIRY"
credit_no = "CREDIT_DEBIT_NUMBER"
date_time = "DATE_TIME"
driver_id = "DRIVER_ID"
ip_add = "IP_ADDRESS"; mac_add = "MAC_ADDRESS"
name = "NAME"; email = "EMAIL"; phone = "PHONE"
passport = "PASSPORT_NUMBER"
pin = "PIN"
ssn = "SSN"
url = "URL"
username = "USERNAME"; password = "PASSWORD"